openshift/cluster-control-plane-machine-set-operator

- OWNERS
This PR adds the initial owners file for this project
> Add initial OWNERS

- pkg/test/cleanup.go
The cleanup tests have been failing, which suggests we need to retry the `DeleteAllOf`. I suspect it's a timing issue within the container restricted build system, because I couldn't reproduce the failure on my local system, but this might make things a little more reliable in CI at least.
> Ensure cleanup retries DeleteAllOf when list still has items

- cmd/control-plane-machine-set-operator/main.go
- pkg/controllers/controlplanemachineset/controller.go
- pkg/controllers/controlplanemachineset/watch_filters.go
- pkg/controllers/controlplanemachineset/watch_filters_test.go
This PR implements required watch filters that allow to distinguish what objects we should reconcile.
> [OCPCLOUD-1492] Implement watch filters 

- pkg/webhooks/controlplanemachineset/webhooks_test.go
This label is required by the Machine controller to be able to create machines, so is validated by the Machine webhook already. However, we also need the cluster ID to be able to name the Machines. Rather than making the user set this twice, re-use the existing API and ensure the value is set through webhook validation.
> Ensure Cluster ID label is set on Machine template

- pkg/webhooks/controlplanemachineset/webhooks.go
- pkg/webhooks/controlplanemachineset/webhooks_test.go
This PR is made up of 2 commits. The first of which is a prefactor to make the second commit easier to work with.
The new content here is a set of validations added so that discriminated unions are validated correctly. IE, when the discriminant is set, only the correct field within the union is set, no extras. This should prevent users from setting invalid configurations
> [OCPCLOUD-1587] Validate discriminated unions via webhooks

- pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/gcp.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/gcp_test.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
This PR implements provider config abstractions for GCP platform. This is almost the same as the one for Azure.
> [OCPCLOUD-1556] Implement provider config abstraction for GCP

- pkg/controllers/controlplanemachineset/updates.go
- pkg/controllers/controlplanemachineset/updates_test.go
This introduces an implementation of the `RollingUpdate` Strategy for the ControlPlaneMachineSet Machines.
> [OCPCLOUD-1502] RollingUpdate Strategy

- pkg/webhooks/controlplanemachineset/webhooks.go
- pkg/webhooks/controlplanemachineset/webhooks_test.go
The failure domain checks within the webhooks are an attempt to prevent immediate rollouts when a ControlPlaneMachineSet is installed. Previously, we have said that the list of failure domains must match exactly with the list of failure domains present within Control Plane Machines.
However, in some regions, the installer would normally configure additional failure domains (eg us-east-1a which has more than 3 failure domains). In this case, it is not harmful to contain the additional failure domains as this would allow balancing later if the control plane were horizontally scaled.
Therefore, this PR changes the behaviour to only prevent the request if there are failure domains that are unused and failure domains that are duplicated within the Machines. This should mean additional failure …
> Ensure additional failure domains do not prevent installation of a ControlPlaneMachineSet

- pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
When gathering Machine Provider information, we should ignore the failure domain comparison when no failure domains were provided in the CPMS. The Machine provider will have no failure domains set in this case so we can use a check against the length of the failure domains to verify this.
This is required to support single availability zone depoyments
> Bug 2115358: Ensure machine provider info can be gathered in a single failure domain

- README.md
This PR adds an initial readme with an overview of the project and some links out to enhancements that are relevant.
I've also added some basic instructions for setting up the project and getting it running on an existing cluster which I think could be useful for some.
> [OCPCLOUD-1657] Add initial readme to repository root

- pkg/controllers/controlplanemachineset/updates.go
- pkg/controllers/controlplanemachineset/updates_test.go
this change adds the body to the `reconcileMachineOnDeleteUpdate` function. it also enables al the tests for this feature as well. with this change users can now enable the OnDelete update strategy.
> Add OnDelete update functionality

- Makefile
Adds targets to Makefile for building the images and pushing to registry. These targets are useful when debugging. It allows you to test your changes in a running cluster by pushing your development images to your quay repository and have cluster deploy them by pointing the CPMS deployment to it.
> Add Make target for building and pushing images

- cmd/control-plane-machine-set-operator/main.go
Webhooks cannot be used when debugging locally, every time I'm trying to debug something I have to manually disable the webhook registrationi by commenting out the code.
Then when I build an image to push to test on the cluster, I forget to uncomment.
This change addresses that irritation by allowing me to configure my debug environment to disable the webhooks, without making code changes every time I'm debugging something.
It has no effect on the product but should make debugging easier for us.
> Add the ability to disable webhook registration

- pkg/controllers/controlplanemachineset/watch_filters.go
These logs messages were recently merged and weren't using structured logs, they should be
> Update log messages to use structured logs

- pkg/machineproviders/providers/machineproviders_test.go
These tests were never implemented and un-pended. This fixes up the tests and marks them as running as exepcted.
We should probably move the subnets, providerspec and failuredomain builders out to the test utils package, they are used frequently and duplicated in many places
> Unpend remaining MachineProvider tests

- test/e2e/common/common.go
- test/e2e/presubmit/presubmit.go
- test/e2e/presubmit_test.go
This adds a check to the E2E suite that confirms that, when a control plane machine does not have the updated status, the control plane machine set reports the correct status but does not delete the Machine.
> [OCPCLOUD-1748] Check OnDelete strategy updates status

- go.mod
- go.sum
- pkg/controllers/controlplanemachineset/controller_test.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
- test/integration/machine_manager.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/core/v1/node.go
- vendor/modules.txt
A CPMS Machine should be considered Ready only when both its underlying MAPI Machine is `Running` **and** the linked Node is `Ready`.
> OCPBUGS-7989: machine's node must be ready for CPMS machine to be ready

- pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
We are currently encountering issues with GCP e2e failures introduced by #175. We currently can't dry-run create the machine to ensure the validity of a providerSpec due to failure domain not being in place for this machine.
> Inject a failure domain into a dry-run created machine

- pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
If the Machine mapping uses valid failure domains, but not necessarily the alphabetically first, we currently would move, eg, b, c, d to a, b, c. This PR deprioritises any failure domain that is not in the machine mapping, which will then mean that we don't rebalance when it is unnecessary
> OCPBUGS-7921: Prioritise machine mapping over alphabetical mapping

- manifests/0000_31_control-plane-machine-set-operator_00_controlplanemachineset.crd.yaml
I am not sure what I'm doing, but I suspect that either this is the right thing to do, or the tooling needs an update.
I am only running this on the main branch to get a sane diff from another PR where this command was run.
Please advise!
> OCPBUGS-12240: Run `make crds-sync`

- pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go
- pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
This is a manual cherry-pick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/198
> [release-4.12] OCPBUGS-12440: Prioritise machine mapping over alphabetical mapping

- pkg/controllers/controlplanemachineset/updates.go
- pkg/controllers/controlplanemachineset/updates_test.go
Previously, for OCPBUGS-4297 (https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/149), we included a check on whether a replacement machine already existed and was not previously detected due to potential stale cache. The check works, and correctly reports a log when a replacement machine is already present, but we actually forgot to include a return, to stop it from creating the actual machine.
> OCPBUGS-7516: fix double machine creation on stale cache

- docs/user/installation.md
Looks like we introduced a new value here in the past (commit 7961d145). Fix numbering, simplifying things somewhat in the process.
> docs: Off-by-one error

- go.mod
- go.sum
- pkg/webhooks/controlplanemachineset/webhooks.go
- pkg/webhooks/controlplanemachineset/webhooks_test.go
- vendor/github.com/openshift/api/config/v1/feature_gates.go
- vendor/github.com/openshift/api/config/v1/types_feature.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/config/v1/infrastructure.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/vsphere_failure_domains.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/openstack_provider_spec.go
- vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/vsphere_provider_spec.go
- vendor/modules.txt
webhook/openstack: add validation for etcd block device size
> OCPCLOUD-2297: webhook/openstack: validate etcd block device size

- docs/user/README.md
- docs/user/failure-domains.md
- docs/user/installation.md
Update documentation with details about vSphere control plane machine set implementation.
> SPLAT-1280: update documentation for vSphere

- .snyk
This change adds a file to configure the snyk automated scans of this repository.
> OCPBUGS-26127: add snyk configuration file

- pkg/controllers/controlplanemachineset/updates.go
- pkg/controllers/controlplanemachineset/updates_test.go
Manual cherry pick of #283 to resolve a conflict in the test files
> [release-4.13] OCPBUGS-30156: Never delete a Machine when there's a single Machine in an index

- pkg/controllers/controlplanemachineset/cluster_operator.go
- pkg/controllers/controlplanemachineset/cluster_operator_test.go
There is an expectation that all cluster operators set at least one namespace and one other object as their related objects. This PR updates our CO generation to set the related objects when they are not as expected.
> NO-JIRA: CPMS Cluster Operator should set related objects

- test/e2e/periodic_test.go
- test/e2e/presubmit_test.go
This PR adds E2E tests (both pre-submit and periodic) for `MachineNamePrefix` feature with `OnDelete` update strategy. 
The existing tests work only for `RollingUpdate` strategy. This PR extends the tests added through:
- https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/338
- https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/332
Part of : https://issues.redhat.com/browse/OAPE-147
> OAPE-147: Add E2E tests for MachineNamePrefix with OnDelete update strategy

- pkg/controllers/controlplanemachinesetgenerator/controller.go
[SPLAT-2079](https://issues.redhat.com//browse/SPLAT-2079)
- Removed VSphereControlPlaneMachineset feature gate
> SPLAT-2079: Removed VSphereControlPlaneMachineset feature gate
