openshift/cluster-control-plane-machine-set-operator

Makefile, cmd/control-plane-machine-set-operator/main.go, pkg/webhooks/controlplanemachineset/suite_test.go, pkg/webhooks/controlplanemachineset/testdata/manifests.yaml, pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
This adds a validating webhook which will later make a number of validations against create and update events for ControlPlaneMachineSet resources.
At the moment, this is just very basic scaffolding for the webhooks, getting them registered and then boilerplate for the test suites.
Note, as the test requires a webhook manifest, I'm using the kubebuilder generator to build this and place it in the testdata folder close to the tests
=> Add basic webhook set up

.golangci.yaml, cmd/control-plane-machine-set-operator/main.go, pkg/controllers/controlplanemachineset/controller.go, pkg/webhooks/controlplanemachineset/suite_test.go, pkg/webhooks/controlplanemachineset/webhooks.go
This adds quite strict linting to the repo which may need tuning over time, but for now this seems to work and takes about 10s on my machine.
The important things I'm trying to achieve:
- Functions aren't super long
- Functions are well documented
- Whitespace is well thought out
- License header is present on all files
- Code duplication is minimised
- 
This config is possibly overly strict but I thought better to do that now and relax it rather than vice-versa.
=> Add golangci-lint configuration for stricter linting

cmd/control-plane-machine-set-operator/main.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/suite_test.go, pkg/controllers/controlplanemachineset/watch_filters.go, pkg/controllers/controlplanemachineset/watch_filters_test.go, pkg/test/resourcebuilder/cluster_operator.go
This PR ensures that the operator is watching the ControlPlaneMachineSet, Machine and ClusterOperator resources which will trigger reconciles.
This is scaffold at the moment as the filters themselves have yet to be implemented, this will be left as a future task. Tests have also been scaffolded, but more tests may be added when the implementation of the watches is done.
=> Scaffold watches for resources in ControlPlaneMachineSet controller

go.mod, pkg/controllers/controlplanemachineset/cluster_operator.go, pkg/controllers/controlplanemachineset/cluster_operator_test.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/status.go, pkg/controllers/controlplanemachineset/suite_test.go, pkg/test/cleanup.go, pkg/test/cleanup_test.go, pkg/test/conditions.go, pkg/test/conditions_test.go, pkg/test/resourcebuilder/cluster_operator.go, pkg/test/suite_test.go
This PR adds a very high level reconcile skeleton of fetching the CPMS, setting the cluster operator status and updating the CPMS status. There is no real logic here but I've added some more test helpers and some tests to cover the ClusterOperator setting the status when there is no CPMS present, this logic should be implemented soon to ensure we can run the operator on a real cluster.
=> Scaffold basic high level reconcile

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/test/cleanup.go, pkg/test/cleanup_test.go, pkg/test/logger.go, pkg/test/logger_test.go
The finalizer is the only spec update we should be doing to the CPMS. So that we avoid conflicts, once we add the finalizer, we should make sure to requeue the object before attempting to reconcile the status in the next reconcile.
This sets up an `ensureFinalizer` function which will need implementing and the pending tests enabling.
=> Ensure the finalizer addition is the first action within the reconcile

go.mod, go.sum, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, vendor/github.com/onsi/gomega/matchers.go, vendor/github.com/onsi/gomega/matchers/have_each_matcher.go, vendor/modules.txt
When a deletion timestamp is set, we expect that the normal reconcile logic will be skipped. This forks the logic into a reconcileDelete function at the beginning. I've also added a couple of tests which outline what we are expecting from the deletion logic.
=> Ensure deletion logic is handled when deletion timestamp is set

pkg/test/conditions.go, pkg/test/conditions_test.go
As we are using metav1.Conditions in the ControlPlaneMachineSet itself, we also need conditions matchers for the metav1.Conditions. Posting this early to make the reviews easier on later PRs.
=> Add conditions matchers for metav1.Condition

pkg/controllers/controlplanemachineset/cluster_operator_test.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/test/cleanup.go, pkg/test/cleanup_test.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
In order to make the cleanup util generic (and any future utils), we should make sure that the test that calls the util should be able to pass in their own Gomega. This will ensure that the util can be reused when a test declares its own Gomega (eg when using `NewWithT`). This is basically an effort to make sure this is generic enough to be copied into other projects/a shared library at some later date.
=> Cleanup utils should not use default Gomega

pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/suite_test.go, pkg/test/resourcebuilder/machine_info.go
This is currently based on #19 and as such, only the last 2 commits need to be reviewed for this PR.
When we have gathered information about the Machines, one part of the operation of the operator is to ensure the owner references on the Machines.
Since this can be done generically (only interacting with ObjectMeta) this part of the logic is in the core of the ControlPlaneMachineSet reconciler and not a part of the Machine provider itself.
I have added tests to define the logic of the `ensureOwnerReferences` function but the remaining logic needs to be implemented still (until the tests pass)
=> Add tests for ensuring owner references on Machines targeted by the ControlPlaneMachineSet

Makefile
Now "make build" fails with error:
```txt
go build -o bin/manager cmd/control-plane-machine-set-operator
cannot find package "." in:
/home/mfedosin/projects/cluster-control-plane-machine-set-operator/vendor/cmd/control-plane-machine-set-operator
make: *** [Makefile:85: build] Error 1
```
This PR fixes it, allowing to successfully build the binary.
=> Fix "build" target in the Makefile

pkg/controllers/controlplanemachineset/status.go, pkg/controllers/controlplanemachineset/status_test.go
This PR adds some additional testing around the status updates to dictate how the log messages will be output when updates are and aren't required.
=> [OCPCLOUD-1496] Add tests for updating status of ControlPlaneMachineSet

.generated_files
This will allow us to ignore generated files and vendor projects while using the prow size plugin, which should add labels to PRs to size them, hopefully helping reviewers to understand how much time they need to spend on a particular review
=> Add generated files configuration

pkg/controllers/controlplanemachineset/status.go, pkg/controllers/controlplanemachineset/status_test.go
This PR allows to update CPMS object status according to the data from MachineInfo.
=> [OCPCLOUD-1496] Implement status reconciliation from MachineInfo

pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go
This PR: 
1. Sets conditionDegraded condition on CPMS CRD when using Recreate or Invalid strategy.
2. Implements machineInfosByIndex function
=> [OCPCLOUD-1498]  Implement supporting functions for reconcileMachineUpdates

pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/machineproviders/types.go, pkg/test/resourcebuilder/control_plane_machine_set.go
Originally, I had asserted that MachineProviders would ensure that the core of the ControlPlaneMachineSet knows about a missing index. This spreads the logic out rather awkwardly. It would be preferable to handle the missing machines directly within the update logic instead.
=> [OCPCLOUD-1523] Ensure missing indexes are included when sorting MachineInfos within updates

hack/verify-log-keys.sh
The previous regex could be greedy and include the closing bracket for a single line declaration with the previous capture group. This would mean it would always capture a second line and second closing bracket which broke the way the script determines there are invalid matches.
=> Ensure log key regex handles single line declarations

.golangci.yaml, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/suite_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/aws_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/suite_test.go, pkg/test/resourcebuilder/aws_provider_spec.go
To enable the core of the openshift machine v1beta1 machine provider to interact with provider configs and failure domains in a generic way, we need to have an interface in front of these that allows a common interface to represent the faliure domains and provider configs of all platforms that we support failure domains on.
This sketches out a skeleton and tests of how this is expected to behave on AWS.
=> [OCPCLOUD-1525] Add AWS Failure Domain and Provider Config skeletons

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/machineproviders/mock/zz_generated_machine_provider_mock.go, pkg/machineproviders/types.go
This means that the context and logger can be passed in for each call to the various MachineProvider functions. Meaning the caller can customise the context and logger rather than having it pinned to the originals passed in when the MachineProvider is constructed.
This is a better pattern as we shouldn't be storing objects like contexts and loggers which have additional context added to them through different callers
=> Add context and logger to MachineProvider interface funcs

pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
This adds the Inject, Extract, Equal and Raw functionality to the provider config abstraction to allow the core of the MachineProvider to be platform agnostic.
These 4 functions represent the needs of the MachineProvider on the provider config.
It will use InjectFailureDomain to take the base provider config and set the correct failure domain before converting it to raw and creating a new machine from it.
It will use ExtractFailureDomain to determine if the failure domain of a Machine is similar to a failure domain it has defined within the CPMS.
It will use Equal to determine if the desired provider config matches that of the Machines it gathers to work out whether they are in need of an update
=> [OCPCLOUD-1558] Extend provider config abstraction to be platform agnostic

pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
This PR expands on how the mapping will work for the failure domains to Machine indexes.
This should give some structure and an outline of the behaviour through the tests that have been added.
Primarily it breaks the mapping down into three stages to be implemented:
- Enumerating the CPMS defined failure domains
- Enumerating the Machine defined failure domains
- Reconciling the two sets of failure domains making sure Machines take precedence
=> [OCPCLOUD-1543] Failure domain mapping

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
Various components within OpenShift expect the machine role label to be present to identify which Machines are Control Plane Machines.
We should enforce consistency here as, if we don't have those labels, other components may not operate correctly.
=> Ensure master role and type label are present on OpenShift Machine Templates

pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/status.go, pkg/controllers/controlplanemachineset/status_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/test/resourcebuilder/node.go
The first few commits in this PR are mainly refactor (and I recommend reviewing commit wise).
The main point of this PR is that there are a couple of scenarios (no ready machines, unmanaged control plane nodes) that should cause the operator to go degraded, we need to make sure this is accounted for.
This PR adds the skeleton for this and then adds tests to ensure the appropriate conditions are set given the scenarios
=> [OCPCLOUD-1565] Ensure invalid cluster state prevents further reconciliation

go.mod, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go, pkg/test/resourcebuilder/aws_provider_spec.go, pkg/test/resourcebuilder/machine.go, pkg/test/resourcebuilder/machine_info.go, pkg/test/resourcebuilder/metadata.go, pkg/test/resourcebuilder/openshift_machine_v1beta1_template.go
This PR introduces testing for the MachineProvider CreateMachine, DeleteMachine and GetMachineInfos methods.
These tests define the core behaviour of the MachineProvider implementation including rules about how the Machines should be named and how to handle various Machine states that the MachineProvider may observe within the cluster
=> [OCPCLOUD-1544] Add OpenShift MachineProvider interface implementation tests

cmd/control-plane-machine-set-operator/main.go, go.mod, manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml, manifests/0000_31_control-plane-machine-set-operator_03_deployment.yaml, manifests/0000_31_control-plane-machine-set-operator_05_service.yaml, manifests/0000_31_control-plane-machine-set-operator_06_webhook.yaml, pkg/controllers/controlplanemachineset/cluster_operator.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, vendor/k8s.io/klog/v2/klogr/README.md, vendor/k8s.io/klog/v2/klogr/klogr.go, vendor/modules.txt
I spent a little time on friday investigating whythe controller was panicking and then attempted to pre verify the webhooks.
It turned out that the panic was due to conditions not existing so I've fixed that in commit 1. Then the webhooks weren't working because we didn't have a ValidatingWebhookConfiguration, commit 2.
On top of this, I noticed the logging was particularly chatty and not in the normal klog format, so I've switched the logging over and used a custom log builder func so that we don't add lots of additional unnecessary context from controller-runtime (eg it adds information about the GVK, we know what that will be already).
Finally, we were missing the watch permission for the clusteroperator resource, so the watches were failing. 
This PR should now make the operator …
=> Bug 2098508: Resolve panics and fix webhooks and logs and watches

docs/contributing.md, pkg/controllers/controlplanemachineset/cluster_operator_test.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/status_test.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go, pkg/test/resourcebuilder/consts.go, pkg/test/resourcebuilder/control_plane_machine_set.go
- **refactor table tests to use cpmsBuilder**
using the cpms pointer was causing issues with not retaining the passed
in values.
- **use lowercase keys for logging**
=> Refactor table tests to use cpmsBuilder, stick to camelCase log key convention

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
This follows up on #43 which introduced the requirement for the two labels. We had intended to make sure that the label and values were as we expect, but we just made sure the label itself was present.
While reviewing https://issues.redhat.com/browse/OCPCLOUD-1438 and the test cases introduced, I realised we had missed the check for the value being something other than `master`, this PR should resolve that issue.
=> Require Machine role and type to be master

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/status.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/test/resourcebuilder/openshift_machine_v1beta1_template.go
This PR implements finalizer addition for CPMS and fixes nil dereference with nil provider spec.
I don't quite understand why handling stale CPMS is required, but hope it's implemented correctly.
=> Implement finalizer addition

.gitignore, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go
Add ownerrefs to machines owned by CPMS. From function TODO: 
```
TODO: Iterate over the MachineInfos, for each Machine, check the owner references for an owner reference matching
that of the current CPMS (it should be the controller so should be easy to find).
If required, look up the GVK using the rest mapper from the GVR, then uses metav1.PartialObjectMetadata to Patch
the owner references. This should mean we can update the metadata of any type given we know the GVR and existing
ObjectMeta.
```
=> Add ownerrefs to machines owned by CPMS

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
This PR adds a check to webhook that ensures that zone from providerSpec matches all control plane machines when custom failure domains are not defined. E.g. Single zone AWS deployments
=> [OCPCLOUD-1622] Ensure zone from providerSpec matches control plane machines

manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml
Without this permission, we cannot update the status of the ControlPlaneMachineSet resources and the operator runs into errors like:
```
E0720 08:32:16.649730       1 controller.go:326]  "msg"="Reconciler error" "error"="error updating control plane machine set status: failed to sync status for control plane machine set object: controlplanemachinesets.machine.openshift.io \"cluster\" is forbidden: User \"system:serviceaccount:openshift-machine-api:control-plane-machine-set-operator\" cannot update resource \"controlplanemachinesets/status\" in API group \"machine.openshift.io\" in the namespace \"openshift-machine-api\"" "controller"="controlplanemachineset" "reconcileID"="062d5457-ffe3-4749-b56e-9110a9b9c10e"
```
=> Allow the operator to update a ControlPlaneMachineSet status subresource

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/machineproviders/providers/machineproviders.go, pkg/test/resourcebuilder/consts.go, pkg/test/resourcebuilder/control_plane_machine_set.go, pkg/test/resourcebuilder/machine.go, pkg/test/resourcebuilder/openshift_machine_v1beta1_template.go
During ControlPlaneMachineSet deletion procedure
reconciler removes owner reference from the machines which it owns.
This pr introduces such logic, related tests and helper functions.
=> [OCPCLOUD-1486] ControlPlaneMachineSet deletion logic

pkg/controllers/controlplanemachineset/controller.go
Add behaviour details for `validateClusterState` implementors around index validity.
=> controller: validateClusterState add behaviour details

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
During QE review, it was noticed that an extraneous `template` was added into the path of this error
=> Remove redundant "template" in error path

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
"template" field in error path was erroneously removed instead of changing it into "spec".
This PR adds the "spec" field to the error path.
=> Add missing "spec" in error path

pkg/controllers/controlplanemachineset/controller_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go, pkg/machineproviders/types.go, vendor/k8s.io/apimachinery/pkg/util/rand/rand.go, vendor/modules.txt
The Machine Provider interface abstracts the machine API specific information out of the core of the CPMS operator.
This commit implements the interface that allows to gather machine information, create and delete machines.
=> [OCPCLOUD-1617] Implement OpenShift Machine Provider Interface for CPMS

manifests/0000_31_control-plane-machine-set-operator_01_rbac.yaml
If you do not have permission to update finalizers within the RBAC, then you get an error when attempting to block owner deletion, this resolved the issue
```
E0802 12:17:14.017740       1 controller.go:326]  "msg"="Reconciler error" "error"="error reconciling control plane machine set: error reconciling machines: error ensuring owner references: error patching machine: machines.machine.openshift.io \"jspeed-test-hmxvx-master-0\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" "controller"="controlplanemachineset" "reconcileID"="5e77308c-244c-4bd9-8573-a9f60d8f868f"
```
Tested manually on AWS
=> [OCPCLOUD-1490] Make sure finalizer RBAC is included for ControlPlaneMachineSet resources

pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
This fixes two things, firstly that we weren't respecting the failure domain mapping from reconcile mappings when a Machine had a different failure domain. This means the rebalancing won't work. We were comparing the failure domain from the machine to failure domain from the machine, where it should have been the failure domain from the mapping.
Secondly, for some reason logging the mapping directly resulted in a map of integers to nil values, the only way I could work out to fix this was to flatten it to a string.
This PR would best be reviewed commit wise
=> Bug 2115638: Ensure that the failure domain mapping is respected in getMachineInfo

pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go
If we know that we aren't going to progress with a rollout, we should degrade the operator.
So, if we can see that a newly created replacement machine errors straight away, for example because the new instance type was invalid, then we should report that and go degraded.
If an existing Machine goes failed, this wouldn't result in degraded as a MachineHealthCheck should cause the Machine to be deleted, and then in that case, we would replace the Machine. Also, if we do go degraded when any Machine is failed, we will not be able to create a replacement Machine if the Failed Machine becomes deleted.
=> Test CPMS degraded when failing to create new Machines

manifests/0000_31_control-plane-machine-set-operator_03_deployment.yaml, manifests/image-references
To allow CPMS operator to be installed by CVO we need to create an
image-references file.
For more information:
https://github.com/openshift/enhancements/blob/master/dev-guide/cluster-version-operator/dev/operators.md#how-do-i-ensure-the-right-images-get-used-by-my-manifests
=> Add image-references

.ci-operator.yaml
This will allow us to manage build root image from the repo.
This is a prerequisite for https://github.com/openshift/release/pull/31146
=> Add .ci-operator.yaml file

pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go
We need to make sure that if there is a machine that has been marked for deletion, that we replace it appropriately.
Therefore, when creating machines, we must include deleting machines from the those we think need replacement and we must exclude deleting machines from the list we think could be replacing an already deleting machine.
This PR updates the rolling update strategy and tests to account for this.
=> [OCPCLOUD-1650] Ensure we replace deleted machines in the RollingUpdate strategy

Dockerfile, cmd/control-plane-machine-set-operator/main.go, pkg/controllers/controlplanemachineset/cluster_operator.go, pkg/controllers/controlplanemachineset/controller.go
Currently we don't copy manifests in the image and therefore CVO can't deploy it.
=> Add manifests in the resulting docker image

pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go
This PR fixes panic when trying to inject nil failure domain and two potential panics when comparing FailureDomains and ProviderConfigs.
=> Bug 2115358: Fix panic when injecting nil FailureDomain

pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go
We need to make sure a number of checks pass before the CPMS controller can perform any operations.
The things to be checked are:
1. **All Nodes in the cluster claiming to be control plane nodes have a valid machine**.
1. **At least 1 of the control plane machines is in the ready state** (if there are no ready Machines then the cluster is likely misconfigured).
1. **The cluster has the correct number of indexes**:
+ Right number of indexes, The cluster state is valid.
+ Too few indexes, The cluster state is valid. We will later scale up without user intervention when we perform reconcileMachineUpdates.
+ Too many indexes, invalid. We set the operator to degraded and ask the user for manual intervention.
1. **No replacement machines** (one that doesn't need update but has an equivalent in …
=> [OCPCLOUD-1647] Implement pre-flight Cluster state validation

pkg/test/resourcebuilder/azure_failure_domains.go, pkg/test/resourcebuilder/azure_provider_spec.go, pkg/test/resourcebuilder/gcp_failure_domains.go, pkg/test/resourcebuilder/openstack_failure_domains.go, pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
We have identified via this bug, that there are two scenarios in which an automated replacement of Control Plane Machines can lead to a broken cluster. Both related to load balancers.
On Azure, the `internalLoadBalancer` has historically not been set by the installer. This is needed (and supported) by Machine API to ensure that the load balancer used by control plane components and kubelet has backends to fulfil the requests. Without this parameter, the CPMS will happily replace all Machines and the cluster will grind to a halt as KCM will lose communication within the API.
On GCP, we have a similar scenario, except updating the internal load balancer backend pool is not currently supported by Machine API on GCP. Until that issue is resolved, we must prevent users installing a CPMS on …
=> Bug 2117439: Add webhook validation to prevent scenarios which can create known broken clusters

Makefile, README.md, hack/test.sh
This change adds a new Makefile target named `test-only` that will run
just the tests with no linting or vendoring activities. It also adds the
`GINKGO_EXTRA_ARGS` environment variable to the `hack/test.sh` script so
that users can inject extra commands to the ginkgo runner.
=> add more options for running tests

pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
When creating new Machines, the MachineProvider was injecting nil failure domains when running without failure domains configured. This meant that on single zone deployments without the `failureDomains` configured, it could not actually create new machines.
This PR resolves the issue by checking if the failure domains are mapped before continuing with the creation.
=> Bug 2115358: Ensure a MachineProvider with no failure domains can create machines

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
This PR fixes some behavior of the Control Plane Machine Set controller around cluster state validation and machine info generation.
- [fix: failed replacement machine test](https://github.com/openshift/cluster-control-plane-machine-set-operator/commit/ef4193080701adafe6cc7e94e48869ef38dd9c24) 
WithError() doesn't automatically set the MachineInfo status to UnReady.
Which is the condition we check on to determine if the replacement is
misbehaving and to later determine if it has errored.
Thus we also need to set WithReady(false).
This closely mimic the real behaviour of the MachineInfo's content
observed in a real cpms cluster.
- [fix: cluster state validation's: checkNoErrorForReplacements](https://github.com/openshift/cluster-control-plane-machine-set-operator/commit/1ab4bb261fdaaa0d8256 …
=> Fix behavior in cluster state validation and machine info generation

pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
A Machine that has not yet been removed from the cluster (ie it has a valid noderef) is typically still ready unless it is failed.
For example, when a Machine is deleted, but the new Machine has not yet come up to replace it, the Machine is still ready as no actions are taken until the etcd operator removes its lifecycle hook.
Currently we go degraded based on a lack of ready machines returned by the machine provider, in the case where a user deletes all machines, this would degrade the operator and we wouldn't automatically replace the deleted machines.
By accepting that a deleted, but previously ready machine is still ready, we can continue operating in this state.
=> Ensure machines that were previously ready are still considered ready

pkg/controllers/controlplanemachineset/controller_test.go
These tests were missed but should have been enabled earlier
=> Enable pending tests for isControlPlaneMachineSetDegraded

Makefile, pkg/cmd/generate/generator.go
Tweaks the cpms generation flow:
- [silence make cpms-generator, so it can be piped to other commands](https://github.com/openshift/cluster-control-plane-machine-set-operator/commit/87b4bd5e057b36c97712c77493e07748521fe5d8)
- [use the KUBECONFIG env var if no --kubeconfig is passed](https://github.com/openshift/cluster-control-plane-machine-set-operator/commit/27a7946a35649081d2f5c0ce616f42857b87f748)
=> Control Plane Machine Set manifest generator tweaks

pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/test/resourcebuilder/machine_info.go
This PR adds logic to handle a corner case where there is more than one machine that is Updated (Ready and Up-to-date) in a single index of the Control Plane Machine Set.
As discussed in the [linked issue](https://issues.redhat.com/browse/OCPBUGS-996), the behaviour, covered by the logic introduced in the PR (last two commits) should be the following:
- at cluster state validation stage, check for every index of the CPMS if there is more than one Updated Machine. If that's the case, carry on if the update strategy is `RollingUpdate` or `Recreate`; if instead the strategy is `OnDelete` log an error and put the operator in degraded state.
- if in `RollingUpdate` or `Recreate` in the respective reconcile logics handle the Updated machine in excess by deleting the oldest between the two. …
=> OCPBUGS-996: Add logic to handle extra updated machines in a single index + minor fixes

docs/user/README.md, docs/user/failure-domains.md
This extends the work started in #92 and adds additional context about failure domains, how they work and how they relate to the cloud provider concepts. It also adds some notes on how a CPMS differs from a regular MS and how the CPMS fits into the Cluster API ecosystem
=> [OCPCLOUD-1570] Add more user documentation about failure domains and FAQs

pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/test/resourcebuilder/machine_info.go
Reverts openshift/cluster-control-plane-machine-set-operator#98 ; tracked by OCPBUGS-1752
Per TRT policy, we are reverting this breaking change to get ci and/or nightly payloads flowing again.  Since this PR merged, aws-sdn-serial has been failing on control plate-related tasks, such as the etcd scaling test which adds an additional control plane node.  Looking at the run history on the PR, the test was also failing in presubmits.  Prior to this merging, this test passed at 95%, and has since dropped to under 60%. https://amd64.ocp.releases.ci.openshift.org/releasestream/4.12.0-0.ci/release/4.12.0-0.ci-2022-09-26-133725 is the first payload that failed, and this looks like the most obvious change to me.
To unrevert this revert, revert this PR, and layer an additional separate commit on …
=> OCPBUGS-996: Reverts "Add logic to handle extra updated machines in a single index + minor fixes"

pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
When failure domains are mapped onto indexes, we first try to assign failure domains of machines to indexes and after that we populate empty indexes with remaining failure domains. We iterate over indexes in ascending order to be consistent.
This caused a bug if you deleted a machine on index 0. The first thing that would happen is it would notice the deleting machine on index 0 and assign its failure domain to the index. Even if there were more machines with that failure domain over the maximum allowed.
To fix this, I have removed machines in deleting phase from affecting failure domain mapping.
=> OCPBUGS-1348: Fix deleting machine affecting new machine failure domain

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
We expect over time that cluster may have renamed their control plane machines, for example rather than being 0, 1, 2, they may now be , 3, 4, 5 or even 2, 4, 6. Previously the CPMS was not handling this and would degrade if it ever saw non 0, 1, 2 indexes.
This PR updates the logic and adds a number of tests to ensure that the entire controller supports these topologies:
* Tests added for full integration checking that the status is set correctly when observing a machine state with various indexes
* Fixed the machineInfosByIndex so that it only adds empty indexes when there aren't the expected number
* Fixed machine provider so that it maps the indexes based on the preferred indexes gathered from the Machines
* Added tests for various parts of the machine provider to check it works as …
=> OCPBUGS-1645: Ensure the ControlPlaneMachineSet can handle machines that are not indexed from 0

.ci-operator.yaml, Dockerfile, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/status.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/test/conditions.go, pkg/test/resourcebuilder/azure_failure_domains.go, pkg/test/resourcebuilder/gcp_failure_domains.go
Cherry-picked from https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/108
Updated comments formatting due to changes in golang 1.19
=> Updating ose-cluster-control-plane-machine-set-operator images to be consistent with ART

pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/generic_platform.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go, pkg/test/resourcebuilder/vsphere_provider_spec.go
This PR allows CPMS to manage control plane machines on all platforms that do not require modification of machine spec for failure domains. 
It does so by creating a generic provider config that contains the spec as RawExtension to allow us to compare machine spec to template spec. 
I've also added resourcebuilder for VSphere for use in test as an example of platform without failure domains.
=> OCPCLOUD-1675: Add support for generic platforms without failure domains

pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
In my previous attempt to fix [OCPBUGS-1348](https://issues.redhat.com/browse/OCPBUGS-1348), I relied on the machine having phase set to "Deleting". For this to be set, it requires the machine to be reconciled by MAO. Unfortunately, CPMS can get the machine before it is reconciled into deleting phase.
I have changed the code to use DeletionTimestamp. It is set by the apiserver when it processes the deletion, so it should be reliably set when CPMS sees the deletion.
=> OCPBUGS-1348: Fix machine not being marked as deleting

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/watch_filters.go, pkg/controllers/controlplanemachineset/watch_filters_test.go
When using `Owns`, the events from the machine objects are filtered so that we only reconcile them if the Machine itself has a controller owner reference pointing at the CPMS.
This works well when the CPMS is `Active`, but when `Inactive`, it means we don't reconcile on Machine events. That means that we don't update the status of the CPMS if Machines are updated (which is when we want to in an `Inactive` state).
This change updates the watch so that we reconcile any control plane machine event regardless of ownership.
I also added some additional logging so that at level 4, we can see when a reconcile is being triggered and by what, this was helpful for debugging.
=> Update watches to include unowned control plane machines

hack/test.sh
We are starting to see that the 2 minutes timeout isn't long enough as we add new tests to various PRs, extending to 5 minutes should give us a little more time to cover the tests we have added
=> Update test timeout to 5 minutes

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
There were two issues at hand here.
The first of the two is that the OnDelete strategy was using the list index rather than machine indexes to create new machines. This would mean, if the machine index was 4 but that was the second item in the list, it would ask to create a new Machine in index 1 (indexed from 0). So the second commit here changes the behaviour of the sorted machine info so that it returns a struct with the machine index rather than just a list of the machine infos, this allows us to get the machine index and loop over that instead.
The second issue was in the way we handled indexes that only contain deleting machines within the provider mapping. We were ignoring them at the wrong stage. By ignoring them in the machine mapping generation, there was no opportunity for the …
=> OCPBUGS-2340: Ensure OnDelete strategy can handle non-standard indexes

manifests/0000_31_control-plane-machine-set-operator_04_clusteroperator.yaml
When running `oc adm must-gather` we do not download controlplanemachineset resources.
Must gather uses `oc adm inspect` under the hood which looks at cluster operator related resources to identify what it should download. In must-gather, it does this across all namespaces.
When gathering across all namespaces, you cannot set a name for the related object else an error is produced:
```
error: errors occurred while gathering data:
skipping gathering controlplanemachinesets.machine.openshift.io/cluster due to error: a resource cannot be retrieved by name across all namespaces
```
We currently set the name of the CPMS in our related objects so we do not get it included in the gather.
=> OCPBUGS-2469: Don't set a name in related objects

pkg/controllers/controlplanemachineset/cluster_operator.go, pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/status.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go
In an effort to improve the observability of errors, this PR sets an error condition on the CPMS status when the reconciler returns an identical error 15 times or more in a row. This happens after approximately 80s since the error first occurs.
This should help reveal spurious errors such as those like when we cannot create a machine because the validation webhooks are failing.
I've manually tested this and it seems to be working as expected.
=> OCPBUGS-2446: Expose an error condition if an error is repeated more than 15 times in a row

pkg/controllers/controlplanemachinesetgenerator/controller_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go, pkg/webhooks/controlplanemachineset/webhooks.go
On upgrade, when we generate a CPMS, there may be more than the initial set of failure domains in the cluster. To prevent duplication, I've updated the failure domain extraction so that it uses a set symantic and returns each failure domain only once.
This prevents scenarios where the CPMS could be configured with the set `{a, b, a, c}` which we have seen in upgrade tests.
=> OCPBUGS-2741: Deduplicate failure domains when generating a ControlPlaneMachineSet

pkg/controllers/controlplanemachinesetgenerator/aws.go, pkg/controllers/controlplanemachinesetgenerator/controller_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set_test.go
If the cluster has control plane machines that do not have a failure domain also represented by the machineset failure domains, then the generator does not include the failure domain for the control plane machine and the CPMS cannot be created.
This updates the failure domain gathering logic to include both the Machine and MachineSet failure domains, so that we create a superset from the two.
This should ensure we always include all available failure domains.
=> OCPBUGS-2854: Ensure generated CPMS includes any failure domain already present in control plane machines

docs/user/README.md, docs/user/installation.md
We recently added the concept of state (Active/Inactive) for the Control Plane Machine Set and we added a new controller responsible for generating the CPMS object for the cluster.
This PR updates the user documentation around the installation flow to account for the recent changes.
The part of the CPMS object description is removed from the installation file as it is already present in the README, linking is updated accordingly.
Note:
I suggest a review starting from the README and navigating through the link to the installation page, to test the flow.
=> OCPCLOUD-1674: Update installation docs to account for generation/activation

pkg/machineproviders/providers/machineproviders_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/set_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go
This PR contains fix that prevents a new master node from getting spawned if we enter duplicate failure domains for CPMS.
I added just one simple case for AWS for now. If we need more, please let me know. I also think that the `set.go` file was wrong - we could have a multiset (a set, where the elements can be more than once) when using `NewSet()` - we could plug a slice that contained duplicates and it would just keep them.
Edit: Also yet to be tested it in the cluster.
=> OCPBUGS-3320: Deduplicate Failure Domains for the CPMS

test/e2e/common/common.go, test/e2e/common/rollingupdate.go, test/e2e/presubmit/presubmit.go, test/e2e/presubmit_test.go
This PR extends the rolling update replacement periodic test to replace a single instance. This test deliberately only tests a single control plane machine replacement as this should be much quicker than a full rolling update. This is cheaper to run as a presubmit vs the full update strategy that exists today.
This is mostly code motion and a copy of the structure of the periodic, just slimming it down to a 30 minute runtime and replacing a single Machine instead of 3.
=> [OCPCLOUD-1747] Add RollingUpdate presubmit to test replacement of outdated machine

test/e2e/common/common.go, test/e2e/framework/framework.go, test/e2e/framework/framework_test.go
Currently, the tests are skipped/fail on Azure because we haven't implemented a way for Azure clusters to be activated (as they are manual) and we haven't added a way to increase the VM size either. This PR does that so that we can E2E test on Azure as well.
=> Add support for Azure e2e tests

pkg/test/resourcebuilder/gcp_provider_spec.go, pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
This PR enables CPMS for GCP, which used to be forbidden before. We check, whether the `targetPools` for GCP aren't empty, if so we append an error accordingly. If everything is correct, then everything goes through just fine. Added some tests for this as well..
I have to test it manually. Will update the PR once I do that:-)
=> [OCPCLOUD-1776]: Enable CPMS for GCP

test/e2e/framework/framework.go, test/e2e/framework/framework_test.go
This PR adds unit tests for scaling the machine sizes on GCP cluster. Also checked whether the e2e presubmit test passes - OK, on a working GCP cluster with CPSM in `Active` state.
=> [OCPCLOUD-1781]: Ensure CPMS tests work on GCP

test/e2e/common/common.go, test/e2e/common/machine.go, test/e2e/presubmit/presubmit.go, test/e2e/presubmit_test.go
This adds a check to the E2E suite that confirms that, when the control plane machine set is deleted, it gets correctly uninstalled and the cluster is cleaned up as expected.
=> OCPCLOUD-1741: e2e presubmit tests: ControlPlaneMachineSet uninstall

test/e2e/presubmit/presubmit.go, test/e2e/presubmit_test.go
This adds a check to the E2E suite that confirms that, when the control plane machine set is recreated after its deletion, all the replicas (control plane machines) are up to date as expected.
This PR is based on https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/138 only the last commit is relevant to this one.
=> OCPCLOUD-1742: e2e presubmit tests: generated ControlPlaneMachineSet replicas updated

test/e2e/framework/utils.go, test/e2e/framework/utils_test.go
This test has been flaking because there was an unstable output in the case the context was cancelled before the timeout was reached.
Either the `Eventually` would catch the timeout in which case the test passed, or, the `checkErr` would be `errContextCancelled` in which case the `StopTrying` returned and the test failed.
By intercepting `errContextCancelled` and returning it plainly, the `Eventually` is always the one catching the context timeout, meaning we now have stable errors.
I also added some context to the `Eventually` so that when it fails it includes the message `check failed or condition did not succeed before the context was cancelled`
=> Ensure stable output from RunCheckUntil

test/e2e/common/machine.go, test/e2e/common/rollingupdate.go, test/e2e/periodic/periodic.go, test/e2e/presubmit/presubmit.go, test/e2e/presubmit_test.go
Currently based on #137, this PR extends the OnDelete strategy test to check that, when we delete a Machine, it gets replaced while the CPMS is configured with an OnDelete strategy. Changes for this PR are the second commit only.
=> [OCPCLOUD-1749] Check on delete strategy correctly replaces machines

hack/test.sh
The unit tests have started overrunning the 5 minute timeout when run across all packages, this should prevent this happening again for a little while.
=> Increase unit test timeout to 10m

test/e2e/presubmit/presubmit.go, test/e2e/presubmit_test.go
This adds a check to the E2E suite that confirms that, when the machines are updated and the control plane machine set is activated, no rollout is triggered.
=> OCPCLOUD-1746: e2e presubmit test: activating ControlPlaneMachineSet doesn't cause rollout

test/e2e/helpers/cases.go, test/e2e/helpers/machine.go, test/e2e/presubmit_test.go
This adds a check to the E2E suite that confirms that, when the machines are up to date and the control plane machine set is activated, the correct owner references are added.
=> OCPCLOUD-1750: e2e presubmit test: activating ControlPlaneMachineSet adds owner references

pkg/controllers/controlplanemachineset/controller_test.go, test/e2e/framework/framework.go, test/e2e/helpers/cases.go, test/e2e/helpers/controlplanemachineset.go, test/e2e/helpers/machine.go, test/e2e/periodic_test.go, test/e2e/presubmit_test.go
This adds a check to the E2E suite that confirms that, when the reference machine (newest, alphabetically latest) provider spec is updated, and the `ControlPlaneMachineSet` is `Inactive`, the `ControlPlaneMachineSet` is regenerated by the `control-plane-machine-set-generator` controller.
=> OCPCLOUD-1744: e2e presubmit: update to newest machine triggers inactive ControlPlaneMachineSet regeneration

cmd/control-plane-machine-set-operator/main.go, pkg/controllers/controlplanemachineset/cluster_operator_test.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/status_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/machineproviders/mock/zz_generated_machine_provider_mock.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/types.go
Fixes issue OCPBUGS-4297, where a stale cache of MachineInfos can lead to the controller not detecting an already existing replacement being present and as such, triggering a subsequent replacement machine creation.
It fixes the issue by introducing an uncached API client which is later used to create an uncached machine provider that checks, right before replacement machine creation (for performance reasons, as we don't want to always use the expensive uncached client), if a replacement already exists, avoiding the double replacement problem.
=> OCPBUGS-4297: Fix stale cache issue on createMachine

pkg/controllers/controlplanemachineset/controller_test.go
Add an integration test for the RollingUpdate strategy where a Machine not needing an update is Deleted, and a replacement for that machine is expected.
=> OCPCLOUD-1752: integration: rollingUpdate: test replaces a not needing update, deleted Machine

pkg/controllers/controlplanemachineset/controller_test.go
Add an integration test for the RollingUpdate strategy where machines are rebalanced across failure domains by the CPMS if they are not balanced as expected.
The PR contains a pre-factor commit and an addition commit, I suggest a per-commit review.
=> OCPCLOUD-1753: integration: rollingUpdate: test rebalances machines across failure domains

docs/developer/test-strategy.md
We developed a [testing strategy](https://docs.google.com/document/d/1nBwmLxDQjV8AZE0XDThp8W2meh9ZPTrX6NxazNMRAGU/edit#heading=h.idcx9qyyu014) document while working out what E2Es we wanted, however this document was previously internal only. I think it should be immortalised in git for the world to see (and so that we can version control it as we make changes in the future.
=> Add testing strategy documentation

pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/test/resourcebuilder/machine_info.go
This reverts commit 606ffb767ab74680e20a74f1cdaf2b6f0ec210e3 and actualizes it with the latest codebase changes. So it reverts the revert in https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/101 which means it actually reintroduces https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/98.
We found out what was causing the issue with the original PR (an etcd vertical scaling test not being compatible with the new CPMS introduction), which is an issue handled separately, and as such we are reintroducing this.
=> OCPBUGS-996: Reverts "Reverts "Add logic to handle extra updated machines in a single index + minor fixes""

Makefile, pkg/controllers/controlplanemachineset/consts.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/test/resourcebuilder/machine_info.go
Manual cherrypick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/112 for release-4.12.
As the automated cherrypick PR is broken https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/157
=> [release-4.12] OCPBUGS-5401: Reverts "Reverts "Add logic to handle extra updated machines in a single index + minor fixes""

hack/e2e.sh, pkg/controllers/controlplanemachineset/controller_test.go, pkg/test/resourcebuilder/configmap.go, pkg/test/resourcebuilder/daemonset.go, pkg/test/resourcebuilder/secret.go, pkg/test/resourcebuilder/service.go, test/e2e/helpers/proxy.go, test/e2e/periodic_test.go, test/e2e/presubmit_test.go
This adds a periodic check to the E2E suite that confirms that, when a cluster wide proxy is configured, the CPMSO is able to create machine replacements, and control plane machines are correctly provisioned by MAPI.
=> OCPCLOUD-1740: e2e periodic test: machine replacement with cluster wide proxy

.golangci.yaml
With the year changing the linter wants us to change the file header's year of all the files touched in a pull request.
With this change we'll accept all years in the file header from 2022 onwards.
=> golangci-lint: fix header year linting

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
This causes issue for private GCP clusters.
We will re-add this check as a warning in the future, when [webhook warnings
are supported by controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/pull/2014). See: https://issues.redhat.com/browse/OCPCLOUD-1894
=> OCPBUGS-6760: webhooks: disable mandatory TargetPools validation on GCP

docs/user/README.md, docs/user/installation.md
For the OCP 4.13 release we are moving the Azure and GCP platforms to "Full" support.
Hence this PRs updates the support matrix and the install steps for these platforms
=> OCPCLOUD-1990: Update supported platforms in docs

cmd/control-plane-machine-set-operator/main.go, hack/test.sh, pkg/controllers/controlplanemachineset/controller.go, pkg/util/suite_test.go, pkg/util/watch_filters.go, pkg/util/watch_filters_test.go
With the recent update in the logic for considering a CPMS replica Ready
only when both the backing Machine is running and the backing Node is
Ready: https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/171, 
we now need to watch nodes at all times to detect nodes
transitioning in readiness.
Also set the SyncPeriod for all the controllers. This way if we miss any transitioning event
we will catch them anyway after the SyncPeriod.
Ancillary changes:
- pkg/util: add test suite
- hack: allow setting TEST_PACKAGES on make invocations
`make unit TEST_PACKAGES="pkg/util <other> <other>"`
=> OCPBUGS-11142: controlplanemachineset: start watching control plane nodes

pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go, test/e2e/framework/framework.go, test/e2e/helpers/controlplanemachineset.go, test/e2e/presubmit_test.go
If we remove the `vmSize` field from the CPMS ProviderSpec on Azure, the master machine gets stuck in a loop of provisiong/deleting states.
We try to fix this by adding a defaulting webhook for Azure's ProviderSpec, specifically for the `vmSize` field. If we see that this field is empty, we provide the ProviderSpec with a default value for that field.
=> OCPBUGS-2960: Check ProviderSpec before generating MachineInfo

pkg/controllers/controlplanemachinesetgenerator/controller.go
When determining the current platform, we should use PlatformStatus instead of PlatformSpec.
=> OCPBUGS-11389: Use PlatformStatus instead of PlatformSpec to determine platform

cmd/control-plane-machine-set-operator/main.go, hack/test.sh, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go, pkg/test/resourcebuilder/node.go, pkg/util/suite_test.go, pkg/util/watch_filters.go, pkg/util/watch_filters_test.go, test/integration/machine_manager.go
A manual backport of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/173 for 4.12
that also includes two other fixes for issues that were introduced by https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/173:
- a backport of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/181
- a backport of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/184
=> [release-4.12] OCPBUGS-8503: machine's node must be ready for CPMS machine to be ready + fixes

pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go
This is a manual cherry-pick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/208
Superseedes https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/209
=> [release-4.12] OCPBUGS-13943: fix double machine creation on stale cache

pkg/controllers/controlplanemachinesetgenerator/controller.go, pkg/controllers/controlplanemachinesetgenerator/controller_test.go, pkg/controllers/controlplanemachinesetgenerator/nutanix.go, pkg/controllers/controlplanemachinesetgenerator/utils.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/nutanix.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, test/e2e/framework/framework.go
This adds basic support for Nutanix control plane machines for the purpose of self-healing control plane nodes. We would enhance this at a later point to add failure domain support.
**How was this tested?**
1. Create a CPMSO image with the changes in  this PR and use the installer built from [installer#7119](https://github.com/openshift/installer/pull/7119)
2. Create a new release image based on a [recent 4.14 release image](registry.ci.openshift.org/ocp/release:4.14.0-0.nightly-2023-04-19-125337) using `oc adm release new --from-release registry.ci.openshift.org/ocp/release:4.14.0-0.nightly-2023-04-19-125337 cluster-control-plane-machine-set-operator=image-registry:cluster-control-plane-machine-set-operator --to-image image-registry:release` and set the release image override environment …
=> [CORS-2666] Add Nutanix support for CPMSO

pkg/controllers/controlplanemachineset/updates_test.go
This fix lint complaining:
```
Found non-compliant log key around ./pkg/controllers/controlplanemachineset/updates_test.go line 1221:10,230. All log keys should be lowerCamelCase.
// 	KeysAndValues: []interface{}{
// 		"updateStrategy", machinev1.RollingUpdate,
// 		"index", int32(1),
// 		"namespace", namespaceName,
// 		"name", "machine-1",
// 		"diff", instanceDiff,
// 	},
```
=> OCPBUGS-15308: Fix lint issue

docs/user/failure-domains.md, docs/user/installation.md, go.mod, go.sum, pkg/controllers/controlplanemachinesetgenerator/controller_test.go, pkg/controllers/controlplanemachinesetgenerator/openstack.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain.go, pkg/machineproviders/providers/openshift/machine/v1beta1/failuredomain/failuredomain_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/openstack.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/openstack_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go, pkg/webhooks/controlplanemachineset/webhooks_test.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1/openstack_failure_domains.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/openstack_provider_spec.go, vendor/modules.txt
Depends on #195 
Depends on https://github.com/openshift/api/pull/1496
=> OSASINFRA-3180: openstack: volume type in failure domain

test/e2e/framework/framework.go
We manage the OpenStack CPMS via the installer, so we can switch the e2e
in Full, so the framework won't create it for us.
Depends-on: https://github.com/openshift/installer/pull/7280
=> e2e: OpenStack CPMS created automatically

test/e2e/framework/framework.go
`VolumeType` is now part of the Failure Domain so we don't want it in
the CPMS Provider Spec.
This was missed in a previous PR.
=> test/e2e: override `RootVolume.VolumeType` to ""

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
In machine-api-operators webhook we have various validations defined for machines, Here we are trying to make use of those validation by running a dry-run to create machine with cpms machine spec.
Sample error when try to edit exiting cpms to remove ami id
```
error: controlplanemachinesets.machine.openshift.io "cluster" could not be patched: admission webhook "controlplanemachineset.machine.openshift.io" denied the request: invalid machine spec: admission webhook "validation.machine.machine.openshift.io" denied the request: providerSpec.ami: Required value: expected providerSpec.ami.id to be populated
```
=> OCPBUGS-18013: Enhance wehbooks to dry run machine creation to validate provider spec

pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
=> OCPCLOUD-2169: Check CPMS events are not present when we expect error

test/e2e/framework/framework.go, test/e2e/framework/framework_test.go
Fixes a test framework failure by adding the GCP instance custom type support to it.
=> OCPBUGS-20070: fix: e2e: add gcp custom type to test framework

test/e2e/framework/framework.go, test/e2e/framework/framework_test.go
Builds upon https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/244
Increases e2-custom memory for when bumping its size, as the current multiplier is too low and results in a machine with too low memory, which results in e2e failures.
=> OCPBUGS-20070: e2e: gcp e2-custom increase memory

test/e2e/framework/framework.go, test/e2e/framework/framework_test.go
Manual backport of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/244 and https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/246
=> [release-4.14] OCPBUGS-20408: fix: e2e: add gcp custom type to test framework

cmd/control-plane-machine-set-operator/main.go, pkg/util/tls.go
This PR aims at removing the offering of deprecated protocols TLS protocol versions (TLSv1, TLSv1.1), from the webhooks endpoints of the operator.
In TLS now there are also cipher suites that are considered weak, making them potentially vulnerable to certain attacks, such as BEAST, LUCKY13 or SWEET32.
These suites in Go are labelled as `InsecureCipherSuites` (see [them here](https://github.com/golang/go/blob/fb726698b7c0255fa5ef62c042c1387c5ff05049/src/crypto/tls/cipher_suites.go#L77-L95)) and are proactively removed from the offered/usable ciphers for TLS encryption. The Go security team keeps them up to date with the most recent security practices.
What ciphers to exclude to prevent BEAST, LUCKY13 or SWEET32 attacks:
- BEAST attacks are only exploitable in TLS 1.0 (TLS 1.1+ have …
=> OCPBUGS-21863: webhooks: set min version TLS 1.2

pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/suite_test.go, pkg/controllers/controlplanemachinesetgenerator/aws.go, pkg/controllers/controlplanemachinesetgenerator/azure.go, pkg/controllers/controlplanemachinesetgenerator/controller.go, pkg/controllers/controlplanemachinesetgenerator/controller_test.go, pkg/controllers/controlplanemachinesetgenerator/gcp.go, pkg/controllers/controlplanemachinesetgenerator/nutanix.go, pkg/controllers/controlplanemachinesetgenerator/openstack.go, pkg/controllers/controlplanemachinesetgenerator/utils.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping.go, pkg/machineproviders/providers/openshift/machine/v1beta1/mapping_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/suite_test.go, pkg/machineproviders/providers/suite_test.go, pkg/test/suite_test.go, pkg/util/infrastructure.go, pkg/util/watch_filters.go, pkg/webhooks/controlplanemachineset/suite_test.go, pkg/webhooks/controlplanemachineset/webhooks.go, test/e2e/framework/framework.go
This PR introduces the infrastructure resource to aid in the resolution of topology and failure domains for platforms such as vSphere.
=> SPLAT-1211: recognize topology and failure domains represented by the infrastructure resource

cmd/control-plane-machine-set-operator/main.go, pkg/util/tls.go
Manual backport of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/252
=> [release-4.14] OCPBUGS-20566: webhooks: set min version TLS 1.2 + exclude weak ciphersuites

go.mod, pkg/webhooks/controlplanemachineset/suite_test.go, pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
This PR implements admission warning for when CPMS providerSpec does not have targetPools field set. This needs to be warning instead of error because on private clusters we don't use target pools.
The warnings are only available as log messages in custom KubeAPIWarningLogger logger that is instantiated from parent logger for controller-runtime when creating client. I added a hook to the parent logger to count the warning messages to enable testing.
=> OCPCLOUD-1894: Implement admission warning for missing target pools

manifests/0000_30_control-plane-machine-set-operator_03_deployment.yaml
All openshift operators must include FallbackToLogsOnError to ease debugging.
=> OCPBUGS-28230: add FallbackToLogsOnError for easier debugging

pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere_test.go
OCPBUGS-29114
- Modified logic when creating new provider config for a machine to trim out static IP content that is not relevant. 
- Keep NetworkName to compare with FailureDomain.
- Keep AddressesFromPools and Nameservers when AddressFromPool is set.  Both are linked for static IPs.
- Updated Unit Tests to check static IP outputs.
https://github.com/openshift/installer/pull/7985
- Installer does have a change to fix the initial definition of the Control Plane Machine Set (CPMS) to no include Nameserver when AddressesFromPools is not set.
=> OCPBUGS-29114: Fixed control plane machine set handling of static IPs when AddressesFromPools is not in use.

pkg/controllers/controlplanemachineset/updates.go, pkg/controllers/controlplanemachineset/updates_test.go
When applying a MachineConfig update, and a CPMS update at the same time, it is possible that the CPMS will prematurely delete a later index, when it is not yet ready to be replaced.
Applying a MachineConfig will drain and reboot the machine, for some period of time, this means the node goes unready.
If we also apply a CPMS change, then all indexes suddenly become outdated.
While replacing index 0, I observed that MCO was updating index 1, therefore the outdated index 1, suddenly became outdated and non ready. Our deletion logic decides that this machine is fit for removal, however, because it has no replacement, this is bad for the cluster. The etcd operator protection does step in, so in my experience, the cluster eventually recovered, but at points, we were down to 2 functional indexes …
=> OCPBUGS-29249: Never delete a Machine when there's a single Machine in an index

go.mod, go.sum, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere_test.go, vendor/github.com/openshift/cluster-api-actuator-pkg/testutils/resourcebuilder/machine/v1beta1/vsphere_provider_spec.go, vendor/modules.txt
[SPLAT-1410](https://issues.redhat.com/browse/SPLAT-1410)
- Modified providerconfig/vsphere.go to keep CPMS machine provider spec networking in order to maintain the AddressesFromPool
- Added log output of networking to allow improved debugging when log level >= 4.
- https://github.com/openshift/cluster-api-actuator-pkg/pull/310
=> SPLAT-1410: Modified vSphere config provider to not lose AddressesFromPools when applying Failure Domains

pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
[OCPBUGS-32295](https://issues.redhat.com/browse/OCPBUGS-32295)
- Modified webhook logic when validating CPMS changes to allow vSphere template to be non path formatted as well.
=> OCPBUGS-32295: Modified webhook to allow templates by name instead of just by path.

pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere_test.go
[OCPBUGS-31808](https://issues.redhat.com/browse/OCPBUGS-31808)
- Added logic to handler older infrastructure definitions where platform spec is not present.
=> OCPBUGS-31808: Fix ExportFailureDomain to handle empty platform spec

pkg/webhooks/controlplanemachineset/suite_test.go, pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
Cherry-Pick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/288
- Modified webhook logic when validating CPMS changes to allow vSphere template to be non path formatted as well.
=> [Release 4.15] OCPBUGS-32357: Modified webhook to allow templates by name instead of just by path.

pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere_test.go, test/e2e/framework/framework.go
Cherry-Pick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/287
- Added logic to handler older infrastructure definitions where platform spec is not present.
=> [Release 4.15] OCPBUGS-32414: Fix ExportFailureDomain to handle empty platform spec

manifests/0000_30_control-plane-machine-set-operator_03_deployment.yaml
References:
- [SCC docs](https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html)
- [SCC pinning docs](https://docs.openshift.com/container-platform/4.15/authentication/managing-security-context-constraints.html#security-context-constraints-requiring_configuring-internal-oauth)
=> AUTH-482: set required-scc for openshift workloads

pkg/webhooks/controlplanemachineset/suite_test.go, pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
[OCPBUGS-32947](https://issues.redhat.com/browse/OCPBUGS-32947)
- Added webhook logic to not allow setting the following values when failure domains are in use:
- datacenter
- datastore
- network (except when defining static IPs)
- server
- Added webhook logic to generate warnings when the following are changed since they may or may not be already set in the failure domain:
- folder
- resource pool
- template
- Enhanced unit tests to cover each of these areas.
- Modified suite_test to allow duplicates of the same warning to allow multiple tests against same warning message
=> OCPBUGS-32947: Modified webhook to reject changes to vsphere fields coming from failure domains.

pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
unreadyNodeGracePeriod is the period in which the node is presumed being unready for a reboot (e.g. during upgrades) or a brief hiccup. This leaves some leeway to avoid immediately reacting on brief node unreadiness.
This strict node readiness checking behaviour was previously introduced when we dediced "machine's node must be ready for CPMS machine to be ready" by https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/171 
How was this tested?
Through the launch of several aggregated payload jobs that perform upgrades.
I did run some before the fix ([1](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/aggregator-periodic-ci-openshift-release-master-ci-4.16-e2e-aws-ovn-upgrade/1788878968938565632)), and some with the fix …
=> OCPBUGS-20061: Add unreadyNodeGracePeriod for allowing brief node hiccups

test/e2e/framework/utils.go, test/e2e/helpers/machine.go
Digging into [this CI run](https://prow.ci.openshift.org/view/gs/test-platform-results/logs/periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.15-periodics-e2e-azure/1796537353917960192) it appears that a non-retryable API error caused the test to fail, when it probably should not have done.
It would be preferable to be able to see what error caused the check to fail, so I'm adding a format string which should print out any errors received.
=> OCPBUGS-35069: Improved debugging of API listing errors

test/e2e/framework/utils.go, test/e2e/helpers/machine.go
One of the utils doesn't exist in 4.14, so had to copy over the `isHTTP2ConnectionLost` helper.
Taking over from #302
=> [release-4.14] OCPBUGS-35338: Improved debugging of API listing errors

test/e2e/helpers/controlplanemachineset.go
Seeing this in presubmits sometimes. One of the tests using this helper expects the CPMS generator to regenerate the CPMS right at the end of the test, but we then immediately call `EnsureControlPlaneMachineSetUpdated` which expects the CPMS to exist.
In the right conditions, this second helper can catch the generator mid way between delete and create as it regenerates, and that causes the test to fail with a not found error.
This should help to prevent that.
=> OCPBUGS-35416: Wait for ControlPlaneMachineSet to be created when waiting for it to be updated

pkg/controllers/controlplanemachineset/controller_test.go, test/e2e/helpers/cases.go, test/e2e/helpers/clusteroperators.go, test/e2e/helpers/formatters.go, test/e2e/periodic_test.go, test/e2e/presubmit_test.go
In recent runs, we are seeing the etcd operator rolls out a new revision immediately after the test completes. This isn't what we intend, but, it doesn't appear that there's a bug in the logic, since the etcd operator eventually stabilises and as does the cluster.
This change is an attempt to make sure that the cluster catches these rollouts, by waiting at least one minute after the last transition of any cluster operator before declaring that the cluster is stable
/hold for testing
=> OCPBUGS-38641: Add 1 minute stabilisation for clusteroperators after rollout

pkg/webhooks/controlplanemachineset/test_util.go, pkg/webhooks/controlplanemachineset/webhooks.go, pkg/webhooks/controlplanemachineset/webhooks_test.go
**Description:**
- Do not block deletion of finalizers due to spec validation
- For vSphere, do not enforce empty provider spec workspace if failure domains are not configured in cpms
=> OCPBUGS-42660: relax validation on delete and if failureDomains not configured

cmd/control-plane-machine-set-operator/main.go, pkg/controllers/controlplanemachineset/cluster_operator_test.go, pkg/controllers/controlplanemachineset/controller.go, pkg/controllers/controlplanemachineset/controller_test.go, pkg/controllers/controlplanemachineset/suite_test.go, pkg/controllers/controlplanemachinesetgenerator/controller_test.go, pkg/machineproviders/providers/machineproviders.go, pkg/machineproviders/providers/machineproviders_test.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go, pkg/util/feature_gate.go, test/e2e/helpers/controlplanemachineset.go, test/e2e/helpers/feature_gate.go, test/e2e/helpers/machine.go, test/e2e/presubmit_test.go
This PR introduces the ability to customize the naming format of Control Plane Machines. This is achieved through a new `machineNamePrefix` field in the ControlPlaneMachineSet spec, gated behind the `CPMSMachineNamePrefix` feature gate.
When feature gate is enabled and `machineNamePrefix` field is specified, it allows users to specify a prefix that will be used in `getMachineName`. The resulting machine name will consist of the provided prefix, followed by a randomly generated string of 5 characters and the machine index.
Otherwise, it will fall back to the default naming convention.
- Implementes : https://github.com/openshift/enhancements/pull/1714
- API PR: https://github.com/openshift/api/pull/2086
- Part of: [OAPE-19](https://issues.redhat.com//browse/OAPE-19)
=> OAPE-19: Support customized control plane machine names with prefix

test/e2e/periodic_test.go
- This is required to gather test data for https://github.com/openshift/enhancements/pull/1714 feature.
- Techpreview periodics job: https://github.com/openshift/release/pull/60342 , https://github.com/openshift/release/pull/60377
- Part of: https://issues.redhat.com/browse/OAPE-78
=> OAPE-78: Add e2e periodic job for machine name prefix

pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
Manual cherry-pick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/340
/assign damdo
/cherrypick release 4.12
=> [release-4.13] OCPBUGS-48259: Add unreadyNodeGracePeriod for allowing brief node hiccups

pkg/machineproviders/providers/openshift/machine/v1beta1/provider.go, pkg/machineproviders/providers/openshift/machine/v1beta1/provider_test.go
This is an manual cherry-pick of https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/342
/assign damdo
=> [release-4.12] OCPBUGS-48325: Add unreadyNodeGracePeriod for allowing brief node hiccups

docs/user/README.md, pkg/controllers/controlplanemachinesetgenerator/controller.go
Update support matrix to include up to date information about providers support.
Nutanix:
- added https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/200/files
- FDs support added: https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/258
VSphere:
- FDs support GAed: https://github.com/openshift/api/pull/1733/
=> NO-JIRA: Update support matrix

pkg/controllers/controlplanemachineset/controller_test.go, test/e2e/framework/framework.go, test/e2e/helpers/controlplanemachineset.go, test/e2e/helpers/machine.go, test/e2e/periodic_test.go, test/e2e/presubmit_test.go
This test assumed that multiple calls to
IncreaseControlPlaneMachineInstanceSize would trigger a rollout every
time. However, this was not true on OpenStack, as flavor names are not
predictable. The OpenStack function assumed it would only ever be called
once, and set a single alternate flavor name passed as an environment
variable. This meant that when called a second time, it did not trigger
a rollout.
In this change we rename the 3 'Increase...InstanceSize' functions to
better reflect their intended function, which is to trigger a rollout.
With this context, we update the OpenStack implementations to add a
random tag instead. This was already the fallback behaviour if no
alternate flavor was passed, and has the additional advantage that it
can be called as many times as required.
Merge …
=> OCPBUGS-50580: Fix MachineNamePrefix periodic on OpenStack

test/e2e/periodic_test.go, test/e2e/presubmit_test.go
Include `CPMSMachineNamePrefix` feature gate name in e2e tests.
This is required for sippy tool to filter the e2e tests specific to this featuregate.
xRef: https://github.com/openshift/api?tab=readme-ov-file#defining-featuregate-e2e-tests
https://issues.redhat.com/browse/OAPE-126
=> OAPE-126: Include CPMSMachineNamePrefix feature-gate name in e2e tests

test/e2e/helpers/cases.go
We are seeing that the 1 minute period is not enough to pick up etcd operator rolling out several revisions.
Increase the stabilisation period to give a 2 minute stable requirement before we accept that the cluster has stabilised
=> OCPBUGS-55017: Wait for operators to be stable for 2 minutes before accepting cluster is stable

pkg/controllers/controlplanemachineset/suite_test.go, pkg/controllers/controlplanemachinesetgenerator/aws.go, pkg/controllers/controlplanemachinesetgenerator/azure.go, pkg/controllers/controlplanemachinesetgenerator/controller.go, pkg/controllers/controlplanemachinesetgenerator/controller_test.go, pkg/controllers/controlplanemachinesetgenerator/gcp.go, pkg/controllers/controlplanemachinesetgenerator/nutanix.go, pkg/controllers/controlplanemachinesetgenerator/openstack.go, pkg/controllers/controlplanemachinesetgenerator/suite_test.go, pkg/controllers/controlplanemachinesetgenerator/utils.go, pkg/controllers/controlplanemachinesetgenerator/utils_test.go, pkg/controllers/controlplanemachinesetgenerator/vsphere.go, pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go, pkg/machineproviders/providers/openshift/machine/v1beta1/suite_test.go
This fixes a bug when a cluster is running with 3 control plane nodes in a single AZ, and machine pools in > 1 AZ, CPMS does not generate a config. 
We decided to remove the feature that gathers additional failure domains from MachineSets. While useful, this feature prevents the generation of the CPMS in the case mentioned above. Our priority is to generate a valid CPMS based on the current state of the control plane, allowing the cluster administrator to add failure domains later if needed, rather than requiring manual intervention upfront.
=> OCPBUGS-52448: Remove gathering of failure domains from machine sets
